const IMAGE_TILE_WIDTH = 16;
const IMAGE_TILE_HEIGHT = 16; 
const PLAYERIMAGE_STATE_TO_ROW ={ 
    idle: 0,
    down: 1,
    up: 2,
    right: 3,
    left: 4,
}

const ALL_RESOLUTIONDIMENSION = 32;

const VIEW_TILE_WIDTH = ALL_RESOLUTIONDIMENSION;
const VIEW_TILE_HEIGHT = ALL_RESOLUTIONDIMENSION;
const PLAYER_START_POZ_X = ALL_RESOLUTIONDIMENSION;
const PLAYER_START_POZ_Y = ALL_RESOLUTIONDIMENSION;